# Codecov configuration. See https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, files"
  require_changes: true
